### ISSUE TITLE
Search Timeout Error in Utah

### ISSUE THREAD

**Issue by Castronova** [CUAHSI/HydroClient#10]
Zoom into Salt Lake City, Utah and search for all keywords and all variables.  The following error occurs.  This seems to happen throughout Utah.

![image](https://cloud.githubusercontent.com/assets/4822372/19969190/0ba0333e-a1ae-11e6-89f7-e8d2adb2ac14.png)

**Comment by ANightCoder-Brian** [comment]
30-Nov-2016 - Problem corrected by other fixes

This issue results from the HydroClient reporting a data service error as a timeout.  Changes in logic for other fixes have corrected this behavior...

**Comment by Lizabrazil** [comment]
This issue still occurs:
![utah issue](https://cloud.githubusercontent.com/assets/13852599/21027590/64e18b38-bd5f-11e6-843e-294d8e90152d.png)

**Comment by ANightCoder-Brian** [comment]
Additional research reveals a different issue from the one originally reported.  

In the current case, incomplete catalog records for the National Oceanic and Atmospheric Administration Service (NOAA) National Climatic Data Center (NCDC) Upper Colorado River Basin Precipitation Service (UCRB_NCDC at http://hiscentral.cuahsi.org/pub_network.aspx?n=242) cause exceptions in map marker clustering logic.  The HydroClient erroneously reports these errors as time outs.

Removal of the incomplete records for the UCRB_NCDC service from the catalog should resolve the issue.
